// <auto-generated />
namespace LibraryLite.UI.Web.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class seedmethod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedmethod));
        
        string IMigrationMetadata.Id
        {
            get { return "201803291247411_seed method"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
